### ISSUE TITLE
Nested arrays

### ISSUE THREAD

**Issue by michaelryancaputo** [bozzltron/node-json-transform#1]
Hey there, great package you have here.

Trying to parse some data that has some nested arrays of objects. I can't seem to find any documentation to set up this type of process.

I would expect to be able to parse data like this, where Category is an array of items, and genericAttrs is an array of objects:

```
  var map = {
    list: 'tv.programme',
    item: {
      title: 'title.0._',
      subTitle: 'sub-title.0._',
      desc: 'desc.0._',
      date: 'date',
      category: [
        {
          list: 'category',
          item: '__text'
        }
      ],
      genericAttrs: [
        {
          list: 'generic_attrs',
          item: {
            name: '_name',
            text: '__text'
          }
        }
      ]
    }
  };
```

**Comment by bozzltron** [comment]
The package does not support that case, but it would be a nice addition.  For now, you can work around by doing multiple transforms.  The original transform, then a transform for category as well as genericAttrs.

**Comment by michaelryancaputo** [comment]
I actually got around it by using the operator to parse that data

**Comment by DouglasParnoff** [comment]
> I actually got around it by using the operator to parse that data

Michael, which operator did works?
