### ISSUE TITLE
Each not working as expected

### ISSUE THREAD

**Issue by Kyberius** [bozzltron/node-json-transform#10]
Hello, I was using your module to parse json, and while using the each functionality I find that don't worked as expected, so I dived a little in the code and change this few lines to work as I wanted, I hope you can include this in your module.

Original code:
`each: function(data) {
    return map.each ? _.each(this.getList(), map.each) : data;
}`

My version of the function:
`each: function(normalized) {
    return map.each ? _.each(normalized, map.each) : normalized;
}`

**Comment by bozzltron** [comment]
Should be fixed with version 1.0.10 thanks!
