### ISSUE TITLE
Promisify and node-json-transform: How to do it properly ?

### ISSUE THREAD

**Issue by fdescamps** [bozzltron/node-json-transform#14]
Hello,

Thanks for this useful tool and all the work around it. Therefore, I have a question.
I would like to know if there is a way to promisify this module with bluebird ?

I wrote two "ways" of doing it but i don't like them because they are not "promise fluent"

```
try{ 
        return BPromise.resolve( DataTransform( dataToTransform, FORMAT_POLICY ).transform() );
    } catch( error  ) {
        return BPromise.reject( error );
    };
```

OR 

```
return new Promise((resolve, reject) => {
         try{ 
            resolve( DataTransform( dataToTransform, FORMAT_POLICY ).transform() );
        } catch( error  ) {
            reject( error );
        };
    });
```

In fact, i had imagined a way like this (where transform or transformAsync is **thenable**) : 
```
const DataTransform = BPromise.promisify('node-json-transform');
return DataTransform( dataToTransform, policyFormat).transformAsync().then((result)=>{
   // ...
}).catch( (error)=> {
   // ...
});
```
... but this does not work.

Thanks by advance,

F.

**Comment by lingwooc** [comment]
This library is blocking so there are no callbacks. This means promisify can't work. Since its just doing a bit of processing this is probably the correct approach.

Your second approach is fine I think. If this library was to use promises it would look just about the same as you have written, just internally. And it would add a dependency. My approach is the same, I just have a helper function to promisify it for me to which I pass the object and map.

**Comment by fdescamps** [comment]
@lingwooc Thanks for the response, i think it's nice thing to put the "second way" in a helper :)

**Comment by jake-tulip** [comment]
One solution is to use this library at the very end of your promises, that is, do all gathering of data (for processing with node-json-transform) with promises, and then this at the very last promise.

There should definitely be support for node-json-transform to allow `operate:` operations to run as promises, as they should be promise-able.

**Comment by churrinfunflais** [comment]
@jake-tulip I'm trying to run a promise with some async work (request-promise) inside an operation with no success, the promise always finish after the hole thing runs,  is there any pattern that you recommend?

```
{
     run: function (val) {
                        return new Promise(resolve => {
                            const rp = require('request-promise');
                            const options = {
                                method: 'POST',
                                uri: '[SOME URI]',
                                headers: {
                                    'cache-control': 'no-cache',
                                    'Content-Type': 'application/xml',
                                    'Authorization': '[SOME AUTH]'
                                },
                                body: '[SOME BODY]'
                            };
                            return rp(options).then(body => {
                                return resolve(body);
                            }).catch(err => {
                                console.err(err);
                            });
                        });
                    },
     on: '[SOME NODE]'
}
```

**Comment by jake-tulip** [comment]
@churrinfunflais I don't think you can return a Promise from a `node-json-transform` `run()` function unfortunately. The `run()` happens internally in the library, and it's just a (callback?) function call, not a Promise resolver.

As I mentioned above, you should run the Promise / asynchronous function outside of the `node-json-transform` `run()`, and then pass that data into the `data` structure. Now you'll have access to this data in the `val`, as an example:

```
  let listOfProducts = [...] // key value pairs to data transform
  const map = {run, on...}

  let promises = [];
  for(let product of listOfProducts) {
    promises.push(fetch("example.com")
      .then(response => {
        product.response = response
        return DataTransform({'data': product}, map).transform().data;
      })
    );
  }

Promise.all(promises).then((products) => {
   doSomethingWithTransformedProducts(products)
   ...
});
```

Then do something like:

your map:
```
const map = {
    'productId': {id: 'product_id', response: 'response'},
};
```

```
{
  run: function (val) {
      doSomething(val.id)
      doSomethingWithResponseData(val.response.data.id)
      return  
     },
  on: '[SOME NODE]'
}
```

**Comment by jake-tulip** [comment]
@churrinfunflais I made a minor edit near the bottom to explain the mapping and how to use the response in the run function.

**Comment by bozzltron** [comment]
Version 1.0.18 implements transformAsync() which returns a promise.
