### ISSUE TITLE
How to transform a map, rather than a list?

### ISSUE THREAD

**Issue by larspai** [bozzltron/node-json-transform#18]
Great module! Maybe I'm missing something in the documentation, but I don't see how to transform a map, which I would think was a simple task. Am I'm missing the obvious? Suppose I have a document that looks like this:
```
{ 
  Id: '2c92c0f95a246217015a29b6b7311576',
  Name: 'New Subscribe Account',
  Subscriptions: 
  [ 
    { 
      Id: '2c92c0f95a246217015a29b6b75d157a',
      Name: 'A-S00000076'
    } 
  ],
  Invoices: 
  [ 
    { 
      Id: '2c92c0855a6b070f015aab4044d65dff',
      Number: 'INV00000063',
      Amount: '8',
      Source: 'BillRun',
      SourceId: 'BR-00000054',
      Items: 
      [
        { 
          Id: '2c92c0855a6b070f015aab4044d95e01',
          ChargeAmount: '1',
          ChargeDate: '2017-03-07T16:10:00-0800',
          SubscriptionId: '2c92c0f95a246217015a29b6b75d157a'
        }
      ] 
    } 
  ] 
}
```
and I need an output along the lines of this:
```
{
   'Account_id': '2c92c0f95a246217015a29b6b7311576',
   'Invoice_id': '2c92c0855a6b070f015aab4044d65dff'
}
```
What should the map look like? (I realize that given the schema of the input document, the output I'm suggesting may produce more than one Invoice_id per Account_id, so an array for Invoice_id's would be appropriate, but this is a bit beside my question...)

**Comment by bozzltron** [comment]
If your data above is stored a variable "data", then you can pass it in like this.

```
var DataTransform = require("node-json-transform").DataTransform;  
var map = { . 
	list : 'accounts',
	item: {
		Account_id: "Id",
		Invoice_id: "Invoices.0.Id"
         }
};
var dataTransform = DataTransform({accounts:[data]}, map);
var result = dataTransform.transform();
console.log(result[0]);
```

**Comment by larspai** [comment]
Ahh! The creation of a "parent" object/array on the call to DataTransform did the trick! Great. Thanks
