### ISSUE TITLE
How to concat 2 values in a single field

### ISSUE THREAD

**Issue by syedshahzebhasnain** [bozzltron/node-json-transform#19]
Hi !

I looked at both the each and operate function,
However, i am not able to understand how to achieve this:
item:{
         name: "name",
         address: "address.city",
         contact: "contact.name" + "contact.phone"
}

**Comment by bozzltron** [comment]
How is the data you are transforming structured?

**Comment by iamlucamilan** [comment]
Hello, i've the same issue with this Json
```
{
    title: "GR1 del 01/11/2017 00:00",
    uniquename: "ContentItem-c708a402-c9d0-487e-af2f-cf5dcb37f512",
    mediauri: "http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=zKhQAYVJ9UQeeqqEEqual",
    date: "20171101",
    hour: "00:00" 
}
```
 I need to concatenate the date and the our and reformat them with moment.js. I've tried with the iterate actions like the example below

```
each: function(item){
    ...
    item.updateDate = moment("date"+"hour").tz("UTC").format();
    ...
```

but I don't figure out if is it possible to access the date and the hour from the source json.

Can you help me?

**Comment by bozzltron** [comment]
The "item" variable passed into the anonymous function will represent and item from the list that you are parsing.  Therefore, item.date and item.hour will be accessible.  You will need to return item after you've made changes for it to take affect.

```
each: function(item){
    item.updateDate = moment(item.date + " " + item.hour, "YYYYMMDD HH:SS").tz("UTC").format();
    return item;
}
```
