### ISSUE TITLE
Unable to completely remove a property

### ISSUE THREAD

**Issue by technicallyfeasible** [bozzltron/node-json-transform#20]
It seems like the only way to set a property to "empty" right now is by using this map:

`
{
  item: {
    clearMe: ''
  }
}
`

This unfortunately sets the target value to an empty string ("") instead of fully removing it.

I would like to have a feature where I can use this definition to fully delete a property from the output:

`
{
  item: {
    clearMe: undefined
  }
}
`

**Comment by bozzltron** [comment]
You can remove items inside of an 'each' function like this.

```
var data = {
  posts: [
    {name: "peter", unwanted: true},
    {name: "paul", unwanted: true},
    {name: "marry", unwanted: true}
  ]
};

var map = {
  list: 'posts',
  each: function(item){
    delete item.unwanted;
    return item;
  }
};

var dataTransform = DataTransform(data, map);

var result = dataTransform.transform();
expect(result).toEqual([
  {name: "peter"},
  {name: "paul"},
  {name: "marry"}
]);
```

**Comment by technicallyfeasible** [comment]
yeah, that's what I'm doing now but it feels clunky, especially that there are already special cases where you can make it an empty string, empty object or empty array

**Comment by bozzltron** [comment]
I am adding a 'remove' feature to the map now.  It will accept an array of keys to attributes that you want to delete on each item.

**Comment by technicallyfeasible** [comment]
that will work, thanks

**Comment by bozzltron** [comment]
1.0.14 supports 'remove'
