### ISSUE TITLE
If a property does not exist in the data it should not be added to the mapped item unless I can set defaults

### ISSUE THREAD

**Issue by technicallyfeasible** [bozzltron/node-json-transform#21]
If I transform data that is missing a mapped property, then the output value is set to "null". This is fine if the property is usually an object but breaks the mapping if the source might be a boolean or number.

`
{ item: { myBoolean: 'originalBoolean' } }
`

If originalBoolean does not exist in the data to be transformed then myBoolean will be set to null.
`
{ myBoolean: null }
`

Expected output:
`{ myBoolean: false }` or `{ }`

**Comment by technicallyfeasible** [comment]
As a solution I would suggest an additional property in the mapping for defaults:

`{ item: { myBoolean: 'originalBoolean' }, defaults: { myBoolean: false } }`

**Comment by bozzltron** [comment]
1.0.14 supports defaults

**Comment by technicallyfeasible** [comment]
I just had a look at the code and it seems there were some console logs left from debugging:

```
		defaultOrNull: function(key) {
			console.log("Use default!");
			let value =  key && map.defaults ? map.defaults[key] : null;
			console.log("default",  map.defaults);
			console.log("key",  key);
			console.log("value", value);
			return value;
		},
```
