### ISSUE TITLE
failed to minify the code with create-react-app

### ISSUE THREAD

**Issue by thg303** [bozzltron/node-json-transform#25]
looks like this code is not es5 compatible, so it can't be minifed. it would be great if it has this feature or else it could not be used with cra as mentioned here:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by bozzltron** [comment]
I just publish 1.0.16 which has a es5 compatibility.

**Comment by thg303** [comment]
thank you @bozzltron  it works like a charm :+1:
