### ISSUE TITLE
Input req.body object as data object, but error 

### ISSUE THREAD

**Issue by fyarepo** [bozzltron/node-json-transform#28]
error: TypeError: Cannot use 'in' operator to search for 'title' in {
                title: "title1",
                description: "description1",
                blog: "This is a blog.",
                date: "11/4/2013",
                extra: {
                    link: "http://goo.cm"
                },
                list1: [
                    {
                        name: "mike"
                    }
                ],
                list2: [
                    {
                        item: "thing"
                    }
                ],
                clearMe: "text"
}

**Comment by bozzltron** [comment]
Could you provide more information?  What data are does your data and map configuration look like?

**Comment by fyarepo** [comment]
Solved, thanks

**Comment by vikasraj789** [comment]
Hi @chunggabriel , Can you tell me how it was solved?

**Comment by vikasraj789** [comment]
Hi @bozzltron Can you tell me how to transform an object? not JSON. I see that there is a 'list' key which works fine only if i pass an array to it. Also please let me know how to omit some properties from original object?

**Comment by bozzltron** [comment]
This test explains how you would do this.  In your case, "posts" is simply an array of one item, which is your object.

```
	it("should exclude data if not specified", function(){
		
		var data = {
			posts: [
				{name: "peter", unwanted: true},
				{name: "paul", unwanted: true},
				{name: "marry", unwanted:true}
			]
		};

		var map = {
			list: 'posts',
			item: {
				name: 'name'
			}
		};

		var dataTransform = DataTransform(data, map);

		var result = dataTransform.transform();

		expect(result).toEqual([
			{name: "peter"},
			{name: "paul"},
			{name: "marry"}
		]);

	});
```
