### ISSUE TITLE
Add ability to pass current object into field

### ISSUE THREAD

**Issue by michaelryancaputo** [bozzltron/node-json-transform#3]
I'm running into a problem where i'm having to run functions on fields to created nested objects within the json file. However, constructing that object is difficult becuase I only have access to what is passed to that field.

`'serviceId': 'serviceId'
    },
    operate: [
      {run: someFunction, on: 'serviceId'},`

So for example I want to run 'someFunction' on serviceId, I can only get access to the items that are supplied to that field, if I want to transform it in some other way, i either need to iterate through the object again supplying more data, or figure out another work around.

Would it be possible to be able to supply a field with an array of documents, this way you could construct an array, or operate on a field containing an array of documents.
Something like this:

`'serviceId': ['serviceId2', 'serviceId1', 'serviceId']`

**Comment by bozzltron** [comment]
So, for example, if you're json input is the following:
{
    "serviceId"    : 0,
    "serviceId1"  : 1,
    "serviceId2"  : 2
}
And the map is as you described.  The output would be the following?
{
    "serviceId" : [ 2, 1, 0 ]
}
You could do object definitions as well.

**Comment by michaelryancaputo** [comment]
Yeah, that would allow you to construct nested objects and/or arrays.

**Comment by bozzltron** [comment]
I've implemented grouping fields into an array in the latest release.

**Comment by michaelryancaputo** [comment]
This is awesome! Thank you!
