### ISSUE TITLE
About the default return value

### ISSUE THREAD

**Issue by bjlee72** [bozzltron/node-json-transform#35]
https://github.com/bozzltron/node-json-transform/blob/1723f8da3357adc0f0ef1597f5866475ee6e7ea6/index.js#L79

If the if block after this line is not executed at all for some reason, the returned result is {}, not []. Because an array is returned for the normal case, it seems a little weird having this empty dictionary is returned for the non-happy case. Shouldn't this be [] instead?

**Comment by bozzltron** [comment]
You are right.  transform() should always return an array.  Fixed in 1.0.17.
