### ISSUE TITLE
cannot use 'in' operator in null

### ISSUE THREAD

**Issue by dolani** [bozzltron/node-json-transform#48]
Mapping  to a response object that returns null always break the code.

i.e response can come as 
`Timeline : { Name : ' ' }`
or 
`Timeline: null`

to transform to 

`item: {
     timeline: {
            name: 'Timeline.Name'
        }`

breaks the code and returns

`Cannot use 'in' operator to search for 'Name' in null`. 

I used default: `{timeline : ' ' }` but still same error.

How do I go about this or am I missing something out?

**Comment by bozzltron** [comment]
I wrote a test to try and replicate.

		var testData = [
			{ Timeline: { Name : 'test'} },
			{ Timeline: null }
		];

		var testMap = {
			list: 'times',
			item: { timeline: { name: 'Timeline.Name' } },
			defaults: {
				timeline: ''
			}
		};
		
		var dataTransform = DataTransform({times: testData}, testMap);
		var result = dataTransform.transform();
		expect(result).toEqual([
			{ timeline: {name: ''} },
			{ timeline: {name: null } }
		]);


I do not get an error.  The result is:

`[ { timeline : { name : 'test' } }, { timeline : { name : undefined } } ] `

**Comment by dolani** [comment]
Got it working now.

I was on an earlier version : 1.0.20. 
It's working fine now on 1.0.21.

Kudos to you on this package. Really helpful.
