### ISSUE TITLE
any option to add two fields into one

### ISSUE THREAD

**Issue by pdl761** [bozzltron/node-json-transform#8]
Like in fieldGroup you are adding two fields and making them array. Similarly is there any option of concatenate two fields and make them one?

**Comment by pdl761** [comment]
I guess you didn't get my question let me explain you by an example
In map file

var map = {
    list : 'posts',
    item: {
        name: "title",
        info: "description",
        text: "blog",
        date: "date",
        link: "extra.link",
        item: "list1.0.name",
        clearMe: "",
        fieldGroup: ['title', 'extra'],
        **_# fieldConcat: 'title'+' '+'extra'          -- I need something like this. Is it possible ?_**
    },
    operate: [
        {
            run: "Date.parse", on: "date",
            run: function(val) { return val + " more info"}, on: "info"
        }
    ]
};

**Comment by bozzltron** [comment]
That is possible.  I will add that in sometime this week.  If you need it right away, you should write a module that extends this module or submit a pull request.

**Comment by pdl761** [comment]
There is one more better way 

In your operate function use this
 **item[method.on] = fn(item);**
Instead of 
 **item[method.on] = fn(item[method.on]);**

and in mapping file use like 
{run: function(**allVal**) {     // give access to all fields and values - so that user can do anything he want
           return **allVal["streetNumber"]+" "+allVal["streetName"];**   // here I can fetch any field I want
              }, on: "streetName"}

and let your items field be like - **streetName: "StreetName"**, no need of specifying here **streetName: "StreetNumber"+" "+"StreetName"**;

**Comment by bozzltron** [comment]
Version 1.0.8 now allows you to specify and "each" function in the map for this purpose.
