### ISSUE TITLE
Properties object same name

### ISSUE THREAD

**Issue by henkiejan** [bozzltron/node-json-transform#9]
I'm having trouble with multiple run operations when I apply the code from the README.md.

It looks to me that there's an errror in this:

operate: [
        {
            run: "Date.parse", on: "date",
            run: function(val) { return val + " more info"}, on: "info"
        }
    ]

This looks to me like an operate array with one object with overlapping property names.
None of the run operations is executed.

This works better:

operate: [
        {
            run: "Date.parse", on: "date"
        },
        {
            run: function(val) { return val + " more info"}, on: "info"
        }
    ]

Now the first run operation is executed, but the second still isn't.

Could you tell me what the correct syntax for multiple operations should be, please?

**Comment by bozzltron** [comment]
The second option is correct.  The first option doesn't work because you've defined "run" and "on" twice.

**Comment by henkiejan** [comment]
Oke, thank you, but what remains is that the documentation in README.md is incorrect.

**Comment by bozzltron** [comment]
I updated the readme and added a new test to confirm multiple operations are working in version 1.0.7.  Thank you.
